### ISSUE TITLE
Color code the health / status information in the supply chain section of workload get

### ISSUE THREAD

**Issue by danfein** [vmware-tanzu/apps-cli-plugin#227]
### Description of problem

As the workload get output gets longer, the risk of folks overlooking important information increases. 
Adding emphasis / visual hierarchy via styling can help call attention to important/helpful bits of information.

### Proposed solution

<Please describe your proposed solution, preferably in the following style:>

```gherkin
Given I check the workload status via workload get
When something is stuck in the supply chain
Then the thing that is stuck should have extra attention called to it
```

### Example

We can use color to indicate good/bad states, making it easy to see at a glance when something is amiss.

for 
Ready column values    : true=green, false=red, unknown=grey
Healthy column values : true=green, false=red, unknown=grey

### Describe alternatives you've considered
If ready is not always an accurate indicator of workload health, we could skip colorizing those values to prevent false alarms. 
ie, if something can be ready=true, but not up-and-running, the green would be misleading. Likewise, if it is possible for something to be not-ready in an expected state, the red might be a false alarm.

Ready column values    : true=white, false=white
Healthy column values : true=green, false=red

**Comment by warango4** [comment]
In a conversation with design, we go to the conclussion that `HEALTHY` column is the one that's going to be colorized. No need to add color to `READY` column since that could somehow mislead users when a workload is, for example, in progress and it's not yet ready. This does not necessarily mean that things are wrong. 

On the other hand, things are either healthy or they are not. So we'll use code color as

true=green/good and false=red/bad
