### ISSUE TITLE
tanzu apps workload delete does not delete image from container registry

### ISSUE THREAD

**Issue by dineshtripathi30** [vmware-tanzu/apps-cli-plugin#79]
### tanzu apps workload delete does not delete image from container registry

I am doing multiple test for deploying sample applications using TAP (tanzu apps workload create) and when deleting those apps workload (tanzu apps workload delete), it does not delete image from container registry. This causes several images on my registry.

### Proposed solution

- I expect the image deletion when workload is deleted. OR atleast there can be an option to take input whether you want to delete image too and let use make the decision. 

```gherkin
Given <Some Condition>
When <Something Happens>
Then <This other thing should happen?>
```

### Example

<Code snippets that illustrate the when/then blocks>

**Comment by atmandhol** [comment]
Hello @dineshtripathi30, Thank you for submitting the issue. The `apps` CLI plugin does not have any knowledge about the images created, and therefore cannot delete it. That is a Cartographer supply chain implementation. You can use the Build service CLI `kp` to delete the build image resources as per the [docs here](https://docs.vmware.com/en/Tanzu-Build-Service/1.5/vmware-tanzu-build-service/GUID-managing-images.html#deleting-an-image-resource). The `kp` CLI will only remove the build resources created to generate the app image. It will not remove the app image itself. You will have to use your OCI repo platform to delete the apps images.

**Comment by scothis** [comment]
If you want to clean up the images created, it's best to publish them into a unique repository and then delete that repository once you are done with it. Automatically deleting the images is difficult because we don't know if or how the images are consumed. Moreover, image registries don't uniformly implement deletion of artifacts as it's very common for layers of one image to depend on layers of another image.
